algoritmo "Raiz Quadrada"

var

// Inicio Declaração de Variáveis
valor : inteiro
raizQuadrada : real
//Fim Declaração de Variáveis

inicio

//Inicio de Entrada de Dados
 valor <- 64
//Fim da Entrada de Dados

//Inico Processamento de Dados
 raizQuadrada <- valor^0.5
//Fim Processamento de Dados

//Inicio Saída de Dados
escreval("Calculando Raizes")
escreval( "Valor" , valor)
escreva( "Raiz", raizQuadrada)
//Fim Saída de Dados

fimalgoritmo
