algoritmo "Bascara"

var
a : real
b : real
c : real
x1 : real
x2 : real
delta : real

inicio
escreva("digite o valor de a: ")
leia(a)
escreva("Digite o valor de b : ")
leia(b)
escreva("Digite o valor de c: ")
leia(c)

delta <- b^2-4*a*c
escreval("Delta",delta)

x1 <- ((-b + (raizQ(delta)))/(2*a)
x2 <- ((-b - (raizQ(delta)))/(2*a)
escreval("x1=",x1)
escreval("x2=",x2)

fimalgoritmo
