algoritmo "exe4"
// Autor :Matheus Witt
// Data : 29/03/2017
var
n1,n2:real
inicio
escreva("Digite um número: ")
leia(n1)
escreva("Digite um segundo número: ")
leia(n2)
limpatela

se(n1 > n2)entao
      escreva("O primeiro numero digitado é o maior")
senao
     se(n2 > n1)entao
        escreva("O segundo numero digitado é o maior")
     senao
        escreva("Os dois numeros digitados são iguais")
     fimse
fimse
fimalgoritmo

